version: "3.7"

services:
  searxng:
    container_name: searxng
    image: searxng/searxng:2025.5.31-93751b6
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - BASE_URL=http://localhost:8080/
      - INSTANCE_NAME=my-instance
    restart: unless-stopped